### ISSUE TITLE
Feature noinline mode and slice and maps of structs

### ISSUE THREAD

**Issue by gorodet-sky** [sethvargo/go-envconfig#102]
I want to implement:
- `noinline` mode for slices and maps, for example:
```sh
export SOME_SLICE_0=a
export SOME_SLICE_1=b
```
```go
type Config struct {
    SomeSlice []string `env:"SOME_SLICE, noinline"`
}

func main() {
  ctx := context.Background()

  var cfg Config
  if err := envconfig.Process(ctx, &cfg); err != nil {
    log.Fatal(err)
  }
  // cfg.SomeSlice = ["a", "b"]
}
```
- slice and maps of structs, it will use the `noinline` mode from the first step, for example:
```sh
export SOME_SLICE_0_PORT=5555
export SOME_SLICE_0_USERNAME=a
export SOME_SLICE_1_PORT=6666
export SOME_SLICE_1_USERNAME=b
```
```go
type NestedStruct struct {
    Port     int    `env:"PORT"`
    Username string `env:"USERNAME"`
}

type Config struct {
    SomeSlice []NestedStruct `env:"SOME_SLICE"`
}

func main() {
  ctx := context.Background()

  var cfg Config
  if err := envconfig.Process(ctx, &cfg); err != nil {
    log.Fatal(err)
  }
  // cfg.SomeSlice[0].Username = "a"
  // cfg.SomeSlice[0].Port= 5555
  // cfg.SomeSlice[1].Username = "b"
  // cfg.SomeSlice[1].Port= 6666
}
```
I think this will be useful in some cases. What do you think about it?

**Comment by sethvargo** [comment]
Hi @gorodet-sky - thank you for opening an issue. Unfortunately I am not going to support this feature, for two reasons:

1. The search space is `O(n)`, and n is 18446744073709551615 (2^64). For each key, we'd need to invoke:

    ```go
    LookupEnv("THING_0")
    LookupEnv("THING_1")
    LookupEnv("THING_2")
    # ...
    LookupEnv("THING_18446744073709551615")
    ```

2. It's not very intuitive. It would be better to specify these values as a native comma-separated slice, or serialize as JSON and then manually decode as JSON during processing.

What are the specific use cases?

**Comment by gorodet-sky** [comment]
> What are the specific use cases?

In our case there are several connections to the database (not all fields in the example), below is an example of a file containing env vars:
```yml
env:
  PG_MASTER_1_HOST: <some_addr>
  PG_MASTER_1_PORT: 5432
  PG_MASTER_1_PRIORITY: 1
  
  PG_MASTER_2_HOST: <some_addr>
  PG_MASTER_2_PORT: 5432
  PG_MASTER_2_PRIORITY: 2
  
  PG_REPLICA_1_HOST: <some_addr>
  PG_REPLICA_1_PORT: 5432
  PG_REPLICA_1_PRIORITY: 1
  
  PG_REPLICA_2_HOST: <some_addr>
  PG_REPLICA_2_PORT: 5432
  PG_REPLICA_2_PRIORITY: 2
```
We can easily change the configuration when the fields of objects are line by line, but the simplest JSON makes clarity suffer.

**Comment by sethvargo** [comment]
Why not:

```yaml
env:
  PG_MASTER_1: 'host:<host>, port:<port>, priority: <priority>'
  PG_MASTER_2: 'host:<host>, port:<port>, priority: <priority>'
  PG_REPLICA_1: 'host:<host>, port:<port>, priority: <priority>'
  PG_REPLICA_2: 'host:<host>, port:<port>, priority: <priority>'
```

That will give you the config as a `map[string]string` which could then be converted into a struct.
